### ISSUE TITLE
Problems since last iTunesConnect Update 

### ISSUE THREAD

**Issue by ghost** [kirbyt/appdailysales#11]
Since last iTunes Connect Update the script doesn't work anymore. Someone here who's good at python

**Comment by mkerley** [comment]
The readme says this project is retired, so you may not get a fix here.

I switched to the [appsome fork](https://github.com/appsome/appdailysales) as a result of the iTunes Connect update.  It's working great.  Though I did have to set up Apple's auto-ingest tool (see [Apple documentation](http://www.apple.com/itunesnews/docs/AppStoreReportingInstructions.pdf)).  You can basically put it in the same directory as the appsome appdailysales.py script and it should be good to go.

**Comment by ghost** [comment]
Sounds good, but on my Server no Java is installed. I contacted the provider....

**Comment by ssuyu** [comment]
Hi  mkerley , I try appsome fork ,but it not work for me. It has some error

File "appdailysales.py", line 338, in ?
    sys.exit(main())
  File "appdailysales.py", line 331, in main
    downloadFile(options)
  File "appdailysales.py", line 255, in downloadFile
    output = subprocess.check_output(
AttributeError: 'module' object has no attribute 'check_output'

**Comment by ghost** [comment]
my error is:

Traceback (most recent call last):
  File "appdailysales.py", line 341, in <module>
    sys.exit(main())
  File "appdailysales.py", line 334, in main
    downloadFile(options)
  File "appdailysales.py", line 259, in downloadFile
    ['java', '-cp', path, 'Autoingestion', appleId, password, vendorId, 'Sales', 'Daily', 'Summary', dateString])
  File "/usr/lib/python2.7/subprocess.py", line 530, in check_output
    process = Popen(stdout=PIPE, _popenargs, *_kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 672, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1213, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by ghost** [comment]
Found a good solution via php
http://www.karlmonaghan.com/2011/09/18/a-sunday-afternoon-project-providing-app-store-stats-via-json/

simply change the datebase table und fields and all is fine
